/**
 * Pure, deterministic helpers for the visa-rule extraction job (SPEC-015 §H).
 * No network, no AI, no I/O — these are the parts of the job that are unit
 * tested. (The AI's *factual* accuracy is gated by human review of the seed
 * diff, not by tests.)
 */

import type { ExtractedVisaRule } from '@/application/ports/visa-rule-extractor';
import type { VisaRuleSeed } from '../db/seed/visa-rule-seed';

export type SanityContext = {
  readonly destination: string; // alpha-3
  readonly knownAlpha3: ReadonlySet<string>;
};

/**
 * Deterministic sanity checks over a single extracted rule. Returns a list of
 * human-readable problems; an empty list means the rule looks internally
 * consistent. These catch model mistakes the Zod schema can't (cross-field
 * coherence), not factual correctness.
 */
export function runSanityChecks(rule: ExtractedVisaRule, ctx: SanityContext): string[] {
  const problems: string[] = [];

  if (ctx.destination.length !== 3) {
    problems.push(`destination "${ctx.destination}" is not an ISO alpha-3 code`);
  }
  if (ctx.knownAlpha3.size > 0 && !ctx.knownAlpha3.has(ctx.destination)) {
    problems.push(`destination "${ctx.destination}" is not in the known country list`);
  }
  if (
    rule.maxStayDays !== null &&
    rule.visaValidityDays !== null &&
    rule.maxStayDays > rule.visaValidityDays
  ) {
    problems.push(
      `maxStayDays (${rule.maxStayDays}) exceeds visaValidityDays (${rule.visaValidityDays})`,
    );
  }
  if (rule.entryType === 'single' && rule.rollingWindow !== null) {
    problems.push('single-entry rule carries a rolling window (usually a multiple-entry concept)');
  }
  if (rule.rollingWindow !== null) {
    if (rule.rollingWindow.allowanceDays > rule.rollingWindow.windowDays) {
      problems.push(
        `rolling allowance (${rule.rollingWindow.allowanceDays}) exceeds window (${rule.rollingWindow.windowDays})`,
      );
    }
  }
  if (rule.minDaysOutBeforeReturn !== null && rule.minDaysOutBeforeReturn < 0) {
    problems.push('minDaysOutBeforeReturn is negative');
  }
  if (
    rule.minAgeYears !== null &&
    rule.maxAgeYears !== null &&
    rule.minAgeYears > rule.maxAgeYears
  ) {
    problems.push(`minAgeYears (${rule.minAgeYears}) exceeds maxAgeYears (${rule.maxAgeYears})`);
  }
  if (rule.purpose === 'working-holiday' && !rule.workRights) {
    problems.push('working-holiday purpose without workRights');
  }
  if (rule.sourceNote.trim().length < 4) {
    problems.push('missing a meaningful sourceNote citation');
  }

  return problems;
}

const BANNER = `/**
 * AUTO-GENERATED by scripts/fetch-visa-rules.ts — do not edit manually.
 *
 * AI-extracted visa rules (source: 'ai-extracted'). Review this file's diff for
 * factual correctness before committing; a reviewer may promote verified rows
 * to source: 'manual' in visa-rule-seed.ts. Re-generate with \`pnpm visa:fetch\`.
 */`;

/**
 * Serialise the extracted seed rows into committable TypeScript. Values are
 * JSON-safe, so `JSON.stringify` yields valid TS object literals.
 */
export function serializeAiSeed(rules: readonly VisaRuleSeed[]): string {
  return [
    BANNER,
    '',
    "import type { VisaRuleSeed } from './visa-rule-seed';",
    '',
    `export const AI_VISA_RULES_SEED: readonly VisaRuleSeed[] = ${JSON.stringify(rules, null, 2)};`,
    '',
  ].join('\n');
}
