/**
 * AUTO-GENERATED by scripts/fetch-visa-rules.ts — do not edit manually.
 *
 * AI-extracted visa rules (source: 'ai-extracted'). Review this file's diff for
 * factual correctness before committing; a reviewer may promote verified rows
 * to source: 'manual' in visa-rule-seed.ts. Re-generate with `pnpm visa:fetch`.
 *
 * Empty until the extraction job is run (SPEC-015 §12 step 10, gated by human
 * review of the broad GBR seed).
 */

import type { VisaRuleSeed } from './visa-rule-seed';

export const AI_VISA_RULES_SEED: readonly VisaRuleSeed[] = [];
